name: ci-golang-workflows # nome do workflow
on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.14", "1.15"]
    steps:
      - uses: actions/checkout@v3 # pega os dados que eu subi e baixa na máquina
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - run: go test ./...
      - run: go run math.go
