name: ci-golang-workflows # nome do workflow
on: [push] # quando rodar o push
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # pega os dados que eu subi e baixa na máquina
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go
